language:
- minimal

script:
- cmake -H. -B_build
- cmake --build _build
- cd _build
- ./main ../misc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data